# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: smtc
      url-base: https://gitlab.semtech.com/Apps-customers/sidewalk

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v2.6.1
      import: true
    - name: sidewalk
      remote: ncs
      repo-path: sdk-sidewalk
      revision: v2.6.1
    - name: lbm431
      remote: smtc
      repo-path: lr11xx-sidewalk-sdk-v2.5.0
      revision: lbm_v431
    - name: lbm450
      remote: smtc
      repo-path: lr11xx-sidewalk-sdk-v2.5.0
      revision: lbm_v450
